services:
  qdrant:
    image: qdrant/qdrant:v1.12.1
    container_name: ouragent-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ouragent-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_storage:/var/lib/rabbitmq

volumes:
  qdrant_storage:
  rabbitmq_storage:
